== The AIR client application
:icons: font
:rootdir: ../../../..
:srcdir: {rootdir}/client-air/src

The client application is a simple Flex application which will publish and receive text messages from a server messaging topic.
It's a single main MXML application which consists in 4 parts:

. Bootstrap the GraniteDS container and configure the client components
. Define the Flex UI
. Define the callback for message reception
. Bind message publishing to the UI

Here is the source code for the first bootstrap/configuration part:

[[client.destination]]
[source,xml,indent=0]
.main/flex/chat.mxml
----
include::{srcdir}/main/flex/chat.mxml[tags=client-setup]
----
<1> This bootstraps the GraniteDS Tide context in the application +preinitialize+ handler. Note that here we use the +Spring+
container integration but it can work with any server technology for most usual operations. However for real applications
with an EJB or CDI server it would be suitable to use the integration classes +Ejb+ and +Cdi+ which provide more specific support.
<2> As the application will run as a desktop AIR application, we have to specify the url and context path of the server.
This is done using the +SimpleServerApp+ definition.
<3> We create a +Consumer+ and a +Producer+ component which are bound to the server topic named +chatTopic+ (see on the
<<server.destination,server application>> where this topic is defined) and configured with a subtopic named +room+.
<4> We have to subscribe the +Consumer+ to its server topic.

The UI is a simple Flex mxml and has no dependency or specific requirement to work with GraniteDS:

[source,xml,indent=0]
.main/flex/chat.mxml
----
include::{srcdir}/main/flex/chat.mxml[tags=client-ui]
----
<1> Pressing on enter triggers the method +send+ that we'll see below
<2> Same for a button click

The interesting part is how to bind the button click and enter key to publish messages:

[source,actionscript,indent=0]
.main/flex/chat.mxml
----
include::{srcdir}/main/flex/chat.mxml[tags=client-publish]
----
<1> We have to create an object of type +AsyncMessage+ and set its +body+ with the data we want to publish.
<2> We send the message using +Producer.send+ with the message object as argument.

The message reception handling is defined in the initialization code and consists in setting a callback method on the
+Consumer+:

[source,actionscript,indent=0]
.main/flex/chat.mxml
----
include::{srcdir}/main/flex/chat.mxml[tags=client-consume]
----
<1> A +MessageEvent.MESSAGE+ event listener is registered and will be called each time a message is received from the
server topic.

Next is the minimal AIR application descriptor:

[source,xml,indent=0]
.main/flex/chat-app.xml
----
include::{srcdir}/main/flex/chat-app.xml
----

Finally here are the necessary maven dependencies and definitions to build the AIR module:
[source,xml,indent=0]
.client-air/pom.xml
----
include::https://raw.github.com/graniteds-tutorials/graniteds-tutorial/master/client-flex/pom.xml[tags=maven-deps]

include::https://raw.github.com/graniteds-tutorials/graniteds-tutorial/master/client-flex/pom.xml[tags=maven-build-air]
----
